### ISSUE TITLE
Cannot Run on macOS 10.12.4, python 2.7.10

### ISSUE THREAD

**Issue by windcloud-409** [Scylardor/cminify#5]
When I run the command `python minifier.py A.cpp`
It returns:
```
Traceback (most recent call last):
  File "minifier.py", line 220, in <module>
    main()
  File "minifier.py", line 217, in main
    minify_source_file(args, filename)
  File "minifier.py", line 185, in minify_source_file
    print(final_string)
UnboundLocalError: local variable 'final_string' referenced before assignment
```
How to fix it?

**Comment by jkarns275** [comment]
I've found that replacing line 185 with "print(intermediate_string)" fixes the issue.

**Comment by Scylardor** [comment]
I'm sorry I'm a bit sick at the moment. I just saw your issue.

I think I passed a bit too quickly on the last pull request. Seems like there's a bug introduced by it.

I'll look into it ASAP, in the meantime, thanks for reporting it. I'm glad you could work around it.

**Comment by Scylardor** [comment]
I rewrote the part that did this.
I fixed the issue it corrected in another way.

I tagged my last commit as 1.0, this is the version that should have all the known issues fixed.
